x = [1,2,3,4,5]

In [1]:
x.append(6)
print(x)

NameError: name 'x' is not defined

In [ ]:
x.pop(2)
print(x)

[1, 2, 4, 5, 6]

In [ ]:
x[::3]

[1, 5]

In [ ]:
y = x[:]

In [ ]:
print(y)

[1, 2, 4, 5, 6]

In [ ]:
del y

In [ ]:
x.insert(2, 3)
print(x)

[1, 2, 3, 4, 5, 6]

In [ ]:
tup = (1,2,3,4,5)

In [ ]:
tup + (6,7)

(1, 2, 3, 4, 5, 6, 7)

In [ ]:
tup[0:6:2]

(1, 3, 5)

In [ ]:
3 in tup

True

In [ ]:
empty = {}

In [ ]:
filled_empty = {"one": 1, "two": 2, "three": 3}

In [ ]:
print(filled_empty)

{'one': 1, 'two': 2, 'three': 3}

In [ ]:
list(filled_empty.values())

[1, 2, 3]

In [ ]:
"one" in filled_empty

True

In [ ]:
"1" in filled_empty

False

In [ ]:
filled_empty.update({"four": 4})
print(filled_empty)

{'one': 1, 'two': 2, 'three': 3, 'four': 4}

In [ ]:
empty_set = set()

In [ ]:
some_set = {1, 1, 2, 2, 3, 4}

In [ ]:
print(some_set)

{1, 2, 3, 4}

In [ ]:
x_set = {6, 7, 8, 9, 10}

In [ ]:
some_set | x_set

{1, 2, 3, 4, 6, 7, 8, 9, 10}

In [ ]:
some_set - x_set

{1, 2, 3, 4}

In [ ]:
some_set >= x_set

False

In [ ]:
var = 5

In [ ]:
if var > 10:
    print("Greater than 10")
elif var < 10:
    print("Less than 10")
else:
    print("Equal to 10")

Less than 10

In [ ]:
"""for loops are used to iterate over a sequence of objects:
dog is a mammal
cat is a mammal
mouse is a mammal
"""
for animal in ["dog", "cat", "mouse"]:
    print("{} is a mammal".format(animal))

dog is a mammal
cat is a mammal
mouse is a mammal

In [ ]:
print("{} is a mammal".format("animal"))

animal is a mammal

In [ ]:
"""
"range(number)" returns a sequence of numbers from 0 to number 
0 1 2 3 4 5 6 7 8 9
"""
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [ ]:
for i in range (4):
    print(i)

0
1
2
3

In [ ]:
for i in range(4, 8, 6):
    print(i)

4

In [ ]:
for i, value in enumerate(["dog", "cat", "mouse"]):
    print(i, value)

0 dog
1 cat
2 mouse

In [ ]:
x= 0
while x < 10:
    print(x)
    x += 1

0
1
2
3
4
5
6
7
8
9

In [ ]:
with open("practice.ipynb") as f:
    for line in f:
        print(line)

{

 "cells": [

  {

   "cell_type": "code",

   "execution_count": 161,

   "metadata": {},

   "outputs": [],

   "source": [

    "x = [1,2,3,4,5]\n"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 162,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "[1, 2, 3, 4, 5, 6]\n"

     ]

    }

   ],

   "source": [

    "x.append(6)\n",

    "print(x)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 163,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "[1, 2, 4, 5, 6]\n"

     ]

    }

   ],

   "source": [

    "x.pop(2)\n",

    "print(x)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 164,

   "metadata": {},

   "outputs": [

    {

     "data": {

      "text/plain": [

       "[1, 5]"

      ]

     },

     "execution_count": 164,

     "metadata": {},

     "output_type": "execute_result"

    }

   ],

   "source": [

    "x[::3]"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 165,

   "metadata": {},

   "outputs": [],

   "source": [

    "y = x[:]"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 166,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "[1, 2, 4, 5, 6]\n"

     ]

    }

   ],

   "source": [

    "print(y)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 167,

   "metadata": {},

   "outputs": [],

   "source": [

    "del y"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 168,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "[1, 2, 3, 4, 5, 6]\n"

     ]

    }

   ],

   "source": [

    "x.insert(2, 3)\n",

    "print(x)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 169,

   "metadata": {},

   "outputs": [],

   "source": [

    "tup = (1,2,3,4,5)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 170,

   "metadata": {},

   "outputs": [

    {

     "data": {

      "text/plain": [

       "(1, 2, 3, 4, 5, 6, 7)"

      ]

     },

     "execution_count": 170,

     "metadata": {},

     "output_type": "execute_result"

    }

   ],

   "source": [

    "tup + (6,7)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 171,

   "metadata": {},

   "outputs": [

    {

     "data": {

      "text/plain": [

       "(1, 3, 5)"

      ]

     },

     "execution_count": 171,

     "metadata": {},

     "output_type": "execute_result"

    }

   ],

   "source": [

    "tup[0:6:2]"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 172,

   "metadata": {},

   "outputs": [

    {

     "data": {

      "text/plain": [

       "True"

      ]

     },

     "execution_count": 172,

     "metadata": {},

     "output_type": "execute_result"

    }

   ],

   "source": [

    "3 in tup"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 173,

   "metadata": {},

   "outputs": [],

   "source": [

    "empty = {}\n"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 174,

   "metadata": {},

   "outputs": [],

   "source": [

    "filled_empty = {\"one\": 1, \"two\": 2, \"three\": 3}"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 175,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "{'one': 1, 'two': 2, 'three': 3}\n"

     ]

    }

   ],

   "source": [

    "print(filled_empty)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 176,

   "metadata": {},

   "outputs": [

    {

     "data": {

      "text/plain": [

       "[1, 2, 3]"

      ]

     },

     "execution_count": 176,

     "metadata": {},

     "output_type": "execute_result"

    }

   ],

   "source": [

    "list(filled_empty.values())"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 177,

   "metadata": {},

   "outputs": [

    {

     "data": {

      "text/plain": [

       "True"

      ]

     },

     "execution_count": 177,

     "metadata": {},

     "output_type": "execute_result"

    }

   ],

   "source": [

    "\"one\" in filled_empty"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 178,

   "metadata": {},

   "outputs": [

    {

     "data": {

      "text/plain": [

       "False"

      ]

     },

     "execution_count": 178,

     "metadata": {},

     "output_type": "execute_result"

    }

   ],

   "source": [

    "\"1\" in filled_empty"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 179,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "{'one': 1, 'two': 2, 'three': 3, 'four': 4}\n"

     ]

    }

   ],

   "source": [

    "filled_empty.update({\"four\": 4})\n",

    "print(filled_empty)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 180,

   "metadata": {},

   "outputs": [],

   "source": [

    "empty_set = set()"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 181,

   "metadata": {},

   "outputs": [],

   "source": [

    "some_set = {1, 1, 2, 2, 3, 4}"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 182,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "{1, 2, 3, 4}\n"

     ]

    }

   ],

   "source": [

    "print(some_set)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 183,

   "metadata": {},

   "outputs": [],

   "source": [

    "x_set = {6, 7, 8, 9, 10}"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 184,

   "metadata": {},

   "outputs": [

    {

     "data": {

      "text/plain": [

       "{1, 2, 3, 4, 6, 7, 8, 9, 10}"

      ]

     },

     "execution_count": 184,

     "metadata": {},

     "output_type": "execute_result"

    }

   ],

   "source": [

    "some_set | x_set"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 186,

   "metadata": {},

   "outputs": [

    {

     "data": {

      "text/plain": [

       "{1, 2, 3, 4}"

      ]

     },

     "execution_count": 186,

     "metadata": {},

     "output_type": "execute_result"

    }

   ],

   "source": [

    "some_set - x_set"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 188,

   "metadata": {},

   "outputs": [

    {

     "data": {

      "text/plain": [

       "False"

      ]

     },

     "execution_count": 188,

     "metadata": {},

     "output_type": "execute_result"

    }

   ],

   "source": [

    "some_set >= x_set"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 189,

   "metadata": {},

   "outputs": [],

   "source": [

    "var = 5"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 192,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "Less than 10\n"

     ]

    }

   ],

   "source": [

    "if var > 10:\n",

    "    print(\"Greater than 10\")\n",

    "elif var < 10:\n",

    "    print(\"Less than 10\")\n",

    "else:\n",

    "    print(\"Equal to 10\")"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 193,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "dog is a mammal\n",

      "cat is a mammal\n",

      "mouse is a mammal\n"

     ]

    }

   ],

   "source": [

    "\"\"\"for loops are used to iterate over a sequence of objects:\n",

    "dog is a mammal\n",

    "cat is a mammal\n",

    "mouse is a mammal\n",

    "\"\"\"\n",

    "for animal in [\"dog\", \"cat\", \"mouse\"]:\n",

    "    print(\"{} is a mammal\".format(animal))"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 197,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "animal is a mammal\n"

     ]

    }

   ],

   "source": [

    "print(\"{} is a mammal\".format(\"animal\"))"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 195,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "0\n",

      "1\n",

      "2\n",

      "3\n",

      "4\n",

      "5\n",

      "6\n",

      "7\n",

      "8\n",

      "9\n"

     ]

    }

   ],

   "source": [

    "\"\"\"\n",

    "\"range(number)\" returns a sequence of numbers from 0 to number \n",

    "0 1 2 3 4 5 6 7 8 9\n",

    "\"\"\"\n",

    "for i in range(10):\n",

    "    print(i)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 198,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "0\n",

      "1\n",

      "2\n",

      "3\n"

     ]

    }

   ],

   "source": [

    "for i in range (4):\n",

    "    print(i)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 202,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "4\n"

     ]

    }

   ],

   "source": [

    "for i in range(4, 8, 6):\n",

    "    print(i)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 203,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "0 dog\n",

      "1 cat\n",

      "2 mouse\n"

     ]

    }

   ],

   "source": [

    "for i, value in enumerate([\"dog\", \"cat\", \"mouse\"]):\n",

    "    print(i, value)"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": 3,

   "metadata": {},

   "outputs": [

    {

     "name": "stdout",

     "output_type": "stream",

     "text": [

      "0\n",

      "1\n",

      "2\n",

      "3\n",

      "4\n",

      "5\n",

      "6\n",

      "7\n",

      "8\n",

      "9\n"

     ]

    }

   ],

   "source": [

    "x= 0\n",

    "while x < 10:\n",

    "    print(x)\n",

    "    x += 1"

   ]

  },

  {

   "cell_type": "code",

   "execution_count": null,

   "metadata": {},

   "outputs": [],

   "source": [

    "with open(\"practice.ipynb\") as f:\n",

    "    for line in f:\n",

    "        print(line)"

   ]

  }

 ],

 "metadata": {

  "kernelspec": {

   "display_name": "base",

   "language": "python",

   "name": "python3"

  },

  "language_info": {

   "codemirror_mode": {

    "name": "ipython",

    "version": 3

   },

   "file_extension": ".py",

   "mimetype": "text/x-python",

   "name": "python",

   "nbconvert_exporter": "python",

   "pygments_lexer": "ipython3",

   "version": "3.10.8"

  },

  "orig_nbformat": 4

 },

 "nbformat": 4,

 "nbformat_minor": 2

}

In [ ]:
contents = {"one": 1, "two": 2, "three": 3}
with open("practice.ipynb", "w") as f:
    f.write(str(contents))

In [ ]:
import json

In [ ]:
with open("practice.ipynb", "w+") as f:
    f.write(json.dumps(contents))

In [ ]:
with open("practice.ipynb", "r") as f:
    contents = json.loads(f.read())
    print(contents)

{'one': 1, 'two': 2, 'three': 3}

In [ ]:
def add(x, y):
    print ("x is {} and y is {}".format(x, y))
    return x + y

In [ ]:
add(5,6)

x is 5 and y is 6

11

In [ ]:
def varargs(*args):
    return args

In [ ]:
varargs(1,2,3,4,5)

(1, 2, 3, 4, 5)

In [ ]:
args = (1,2,3,4,5)
kwargs = {"one": 1, "two": 2, "three": 3}

In [ ]:
def swap(x, y):
    return y, x

In [ ]:
import plotly.express as px

In [ ]:
g = px.data.election()
g

,district,Coderre,Bergeron,Joly,total,winner,result,district_id
0,101-Bois-de-Liesse,2481,1829,3024,7334,Joly,plurality,101
1,102-Cap-Saint-Jacques,2525,1163,2675,6363,Joly,plurality,102
2,11-Sault-au-Récollet,3348,2770,2532,8650,Coderre,plurality,11
3,111-Mile-End,1734,4782,2514,9030,Bergeron,majority,111
4,112-DeLorimier,1770,5933,3044,10747,Bergeron,majority,112
5,113-Jeanne-Mance,1455,3599,2316,7370,Bergeron,plurality,113
6,12-Saint-Sulpice,3252,2521,2543,8316,Coderre,plurality,12
7,121-La Pointe-aux-Prairies,5456,1760,3330,10546,Coderre,majority,121
8,122-Pointe-aux-Trembles,4734,1879,2852,9465,Coderre,majority,122
9,123-Rivière-des-Prairies,5737,958,1656,8351,Coderre,majority,123
10,13-Ahuntsic,2979,3430,2873,9282,Bergeron,plurality,13
11,131-Saint-Édouard,1827,6408,2815,11050,Bergeron,majority,131
12,132-Étienne-Desmarteau,2331,5748,2788,10867,Bergeron,majority,132
13,133-Vieux-Rosemont,2670,4962,3234,10866,Bergeron,plurality,133
14,134-Marie-Victorin,3673,3155,2431,9259,Coderre,plurality,134
15,14-Bordeaux-Cartierville,3612,1554,2081,7247,Coderre,plurality,14
16,141-Côte-de-Liesse,4308,1320,3959,9587,Coderre,plurality,141
17,142-Norman-McLaren,4104,1459,2822,8385,Coderre,plurality,142
18,151-Saint-Léonard-Est,3931,882,1641,6454,Coderre,majority,151
19,152-Saint-Léonard-Ouest,5387,1184,1908,8479,Coderre,majority,152
20,161-Saint-HenriPetite-BourgognePointe-Saint-Ch...,2432,3368,3578,9378,Joly,plurality,161
21,162-Saint-PaulÉmard,2566,2092,2438,7096,Coderre,plurality,162
22,171-ChamplainL'Île-des-Soeurs,3347,2562,3291,9200,Coderre,plurality,171
23,172-Desmarchais-Crawford,2476,2631,2849,7956,Joly,plurality,172
24,181-Peter-McGill,1451,754,1894,4099,Joly,plurality,181
25,182-Saint-Jacques,1906,2169,2282,6357,Joly,plurality,182
26,183-Sainte-Marie,1347,2827,2271,6445,Bergeron,plurality,183
27,191-Saint-Michel,3668,984,1220,5872,Coderre,majority,191
28,192-François-Perrault,2878,2666,2039,7583,Coderre,plurality,192
29,193-Villeray,2201,5819,2782,10802,Bergeron,majority,193
30,194-Parc-Extension,2420,1793,1402,5615,Coderre,plurality,194
31,21-Ouest,2184,691,1076,3951,Coderre,majority,21
32,22-Est,1589,708,1172,3469,Coderre,plurality,22
33,23-Centre,2526,851,1286,4663,Coderre,majority,23
34,31-Darlington,1873,1182,1232,4287,Coderre,plurality,31
35,32-Côte-des-Neiges,1644,1950,1578,5172,Bergeron,plurality,32
36,33-Snowdon,1548,1503,1636,4687,Joly,plurality,33
37,34-Notre-Dame-de-Grâce,1773,2653,3262,7688,Joly,plurality,34
38,35-Loyola,2040,1437,2648,6125,Joly,plurality,35
39,41-du Canal,1165,832,1266,3263,Joly,plurality,41
40,42-J.-Émery-Provost,1193,653,1157,3003,Coderre,plurality,42
41,43-Fort-Rolland,1325,1205,1908,4438,Joly,plurality,43
42,51-Sault-Saint-Louis,4201,1642,3717,9560,Coderre,plurality,51
43,52-Cecil-P.-Newman,3536,1330,2943,7809,Coderre,plurality,52
44,61-Pierre-Foretier,631,258,998,1887,Joly,majority,61
45,62-Denis-Benjamin-Viger,595,226,1068,1889,Joly,majority,62
46,63-Jacques-Bizard,518,224,690,1432,Joly,plurality,63
47,64-Sainte-Geneviève,332,131,326,789,Coderre,plurality,64
48,71-Tétreaultville,3694,2589,3454,9737,Coderre,plurality,71
49,72-MaisonneuveLongue-Pointe,2746,3250,3139,9135,Bergeron,plurality,72
50,73-Hochelaga,1546,3679,2675,7900,Bergeron,plurality,73
51,74-Louis-Riel,3509,2178,2338,8025,Coderre,plurality,74
52,81-Marie-Clarac,6591,1085,1435,9111,Coderre,majority,81
53,82-Ovide-Clermont,6229,780,1051,8060,Coderre,majority,82
54,91-Claude-Ryan,996,643,423,2062,Coderre,plurality,91
55,92-Joseph-Beaubien,540,833,592,1965,Bergeron,plurality,92
56,93-Robert-Bourassa,446,465,419,1330,Bergeron,plurality,93
57,94-Jeanne-Sauvé,491,698,489,1678,Bergeron,plurality,94

In [2]:
import pandas as pd
print(pd.options.display.max_rows)

60